const pgp = require("pg-promise")();
require("dotenv").config();

var connectionOptions = {
  connectionString: process.env.DATABASE_URL,
  max: 10, // poolSize
  idleTimeoutMillis: 10000 // poolIdleTimeout
};

try {
  var db = pgp(connectionOptions);
  if (db) {
    db.oneOrNone("SET TIME ZONE 'US/Eastern';SELECT current_setting('TIMEZONE') AS current_timezone;")
      .then(res => console.log("database timezone", res))
      .catch(error => console.error("error setting timezone", error));
  }
} catch (error) {
  console.error("database connection error", error);
}
/*
log level 
0 = normal
1 = warning
2 = user error
3 = system error
4 = code block error catch
*/
const logging = (message, line_at, level = 0) => {
  (async () => {
    let session = null;
    try {
      // Acquire a new session
      session = await db.connect({ direct: true });
      // Start a transaction within the session
      await session.tx(async t => {
        // Execute the INSERT query
        const insertQuery = `
          INSERT INTO web_host_running_log
          (level, message, code_line_at)
          VALUES
          ($[level], $[message], $[code_line_at]);
        `;
        t.one(insertQuery, { message, line_at, level })

      });
    } catch (error) {
      console.error('Error inserting data:', error);
    } finally {
      // Release the session
      if (session) {
        session.done(); // Release the session back to the pool
      }
    }
  })()
}

module.exports = { db, logging };
/*
-- DDL generated by Postico 2.1
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE web_host_running_log (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    level integer DEFAULT 0,
    message text,
    create_at timestamp with time zone DEFAULT now(),
    code_line_at text
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX web_host_running_log_pkey ON web_host_running_log(id int4_ops);

*/